### PR TITLE
update to csproj and asp.net core 2.0

### PR DESCRIPTION
**Pull request by SychevIgor**
update to csproj VS2015 -> VS2017, Asp.net Core 1.0-> 1.1

### CODE REVIEW

**Comment by SychevIgor** [comment]
@dstrockis @priyamohanram @polita anybody still supporting this repo or it's officially not supported... ?

**Comment by jmprieur** [comment]
@SychevIgor : it got assigned to me two days ago. How can I help? https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore/commit/6088894ab3bce062f313d88ec45c1251534c83b7
cc: @dstrockis

**Comment by SychevIgor** [comment]
@jmprieur it will be great if you will merge or close this PR(if course with an explanation what is wong with it)... if we need some update of this PR- tell me and I will update it, because otherwise it looks like repo is dead an not maintained.

**Comment by SychevIgor** [comment]
nobody care

**Comment by jmprieur** [comment]
_@SychevIgor_ : sorry for the impression we have been giving. We do care. we have not got to this yet in our priority list.

**Pull request closed without merging**
